
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: serviceadmin
#     version: "1.0"
#   name: serviceadmin
# spec:
#   replicas: 1  # Set the number of replicas
#   selector:
#     matchLabels:
#       app: serviceadmin
#   template:
#     metadata:
#       labels:
#         app: serviceadmin
#     spec:
#       containers:
#         - name: serviceadmin
#           image: hamamebch/rental-manager:0.1
#           imagePullPolicy: IfNotPresent
#           ports:
#             - containerPort: 3000
#           env:
#             - name: MONGO_URI
#               valueFrom:
#                 secretKeyRef:
#                   name: mongodb-secret
#                   key: MONGO_URI
#             - name: PORT
#               value: 3000

#             - name: CLOUDINARY_CLOUD_NAME
#               valueFrom:
#                 secretKeyRef:
#                   name: cloudinary-secret
#                   key: CLOUDINARY_CLOUD_NAME
#             - name: CLOUDINARY_API_KEY
#               valueFrom:
#                 secretKeyRef:
#                   name: cloudinary-secret
#                   key: CLOUDINARY_API_KEY
#             - name: CLOUDINARY_API_SECRET
#               valueFrom:
#                 secretKeyRef:
#                   name: cloudinary-secret
#                   key: CLOUDINARY_API_SECRET
#           resources: {}
#       restartPolicy: Always
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: serviceadmin
#   name: serviceadmin
# spec:
#   ports:
#     - port: 80
#       protocol: TCP
#       targetPort: 3000
#       name: http
#   selector:
#     app: serviceadmin
#   type: NodePort  





apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: serviceuser
    version: "1.0"
  name: serviceuser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceuser
  template:
    metadata:
      labels:
        app: serviceuser
    spec:
      containers:
        - name: serviceuser
          image: boualem775/servicerental:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI
            - name: PORT
              value: "8081"

            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_API_SECRET
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: serviceuser
  name: serviceuser
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
      name: http
  selector:
    app: serviceuser
  type: NodePort




  
